export const constants = {
  CREATE_USER: "CREATE_USER",
  MOVE_USER: "MOVE_USER",
  EVACUATE_USERS: "EVACUATE_USERS",
  CREATE_FLOOR: "CREATE_FLOOR",
  DELETE_FLOOR: "DELETE_FLOOR",
  GET_UNUSED_APARTMENTS: "GET_UNUSED_APARTMENTS",
  FILL_APARTMENT: "FILL_APARTMENT",
};
